# Generated by Django 4.1.1 on 2022-10-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0003_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='User',
        ),
    ]
