# Generated by Django 4.1.1 on 2022-10-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0004_rename_manager_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstusername_name',
            new_name='first_name',
        ),
    ]
