# Generated by Django 4.1.1 on 2022-10-01 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0005_rename_firstusername_name_user_first_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Manager',
        ),
    ]
