# Generated by Django 4.1.1 on 2022-10-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0006_rename_user_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Account',
        ),
    ]
