# Generated by Django 4.1.1 on 2022-10-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0008_account_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
