# Generated by Django 4.1.1 on 2022-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0010_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/managers/default.jpg', null=True, upload_to='static/managers/'),
        ),
    ]
