# Generated by Django 4.1.1 on 2022-10-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0011_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='avtar',
        ),
    ]
