# Generated by Django 4.1.1 on 2022-10-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0014_mannager_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannager',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
