# Generated by Django 4.1.1 on 2022-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0016_alter_mannager_email_alter_mannager_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannager',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mannager',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
