# Generated by Django 4.1.1 on 2022-10-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0017_alter_mannager_email_alter_mannager_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mannager',
            name='email',
        ),
    ]
