# Generated by Django 4.1.1 on 2022-10-11 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weblog_app', '0018_remove_mannager_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mannager',
            new_name='Manager',
        ),
    ]
