# Generated by Django 4.1.1 on 2022-10-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0021_rename_image_manager_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, default='managers/default.jpg', null=True, upload_to='managers/'),
        ),
    ]
