# Generated by Django 4.1.1 on 2022-10-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0026_alter_manager_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(default='managers/default.jpg', upload_to='managers/'),
        ),
    ]
