# Generated by Django 4.1.1 on 2022-10-25 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0031_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/uploads/team/logo.png', null=True, upload_to='uploads/team/')),
                ('name', models.CharField(max_length=50)),
                ('N_Matches', models.IntegerField(default=0)),
                ('N_Wins', models.IntegerField(default=0)),
                ('N_Draws', models.IntegerField(default=0)),
                ('N_Losses', models.IntegerField(default=0)),
                ('Score_P', models.IntegerField(default=0)),
                ('Score_M', models.IntegerField(default=0)),
                ('Points', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblog_app.manager')),
                ('season_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog_app.season_name')),
            ],
        ),
    ]
