# Generated by Django 4.1.1 on 2022-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0041_match_delete_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
