# Generated by Django 4.1.1 on 2022-11-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0042_alter_match_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='body',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
