# Generated by Django 4.1.1 on 2022-11-15 12:51

from django.db import migrations, models
import weblog_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0052_alter_manager_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(default='managers/default.png', help_text='Please use our recommended dimensions: 1140 x 425 PX, 250 KB MAX', upload_to='managers/', validators=[weblog_app.models.validate_image]),
        ),
    ]
