# Generated by Django 3.2.16 on 2022-12-02 22:15

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0053_alter_manager_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='season_name',
            new_name='new_season_name',
        ),
        migrations.AlterField(
            model_name='match',
            name='Team_home',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='new_season_name', chained_model_field='Season_name', on_delete=django.db.models.deletion.CASCADE, to='weblog_app.team'),
        ),
    ]
