# Generated by Django 3.2.16 on 2022-12-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0055_auto_20221202_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='weblog_app.team'),
        ),
    ]
