# Generated by Django 3.2.16 on 2022-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0056_alter_match_team_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
