# Generated by Django 3.2.16 on 2022-12-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0057_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Score',
        ),
    ]
